name: CI Dev

on:
  pull_request:
    branches:
      - master
      
jobs:
# test:
#   ...
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
